### ISSUE TITLE
Allow to specify podman runtime options on the commandline

### ISSUE THREAD

**Issue by schaefi** [Elektrobit/oci-pilot#41]
# Description

As of today the runtime options passed to podman can be added in the flake file as follows:

```yaml
runtime:
  podman:
    - setting
    - setting
    - setting
```

There is no way to specify runtime settings on the commandline during ```oci-ctl register ...```

# Acceptance Criteria

* A commandline switch to add a runtime setting during app registration exists
* The commandline setting can be added multiple times
