### ISSUE TITLE
Add support for include section in flake file

### ISSUE THREAD

**Issue by schaefi** [Elektrobit/oci-pilot#52]
# Description

Allow to include files as part of the container provisioning e.g

```yaml
include:
  tar:
    - tar-archive-to-include
  file:
    - file/to/include
  ...and_so_on
```

# Acceptance Criteria

- An include statement in the flake file gets evaluated by oci-pilot
- At least one include format is implemented, starting with ```tar```
