### ISSUE TITLE
Allow to specify user identity for running the app

### ISSUE THREAD

**Issue by schaefi** [Elektrobit/oci-pilot#54]
# Description

As of today the user id to run the engine is specified in the flake setup as follows:

```yaml
container:
  runtime:
    runas: root
```

There is no option to specify the user on the commandline

# Acceptance Criteria

* User ID can be specified at registration time for the supported engines
